/**
 * Spaced-repetition flashcards for the Human Design library.
 *
 * Structural facts follow the canonical reference data in
 * `@/lib/human-design/constants` (centre → gates, the 36 channels, lines and
 * profiles). Each card carries a difficulty of 1 (recall), 2 (application) or
 * 3 (interpretation).
 */

export type FlashcardDifficulty = 1 | 2 | 3;

export interface Flashcard {
  id: string;
  deck: string;
  front: string;
  back: string;
  tags: string[];
  difficulty: FlashcardDifficulty;
}

export const DECKS: readonly string[] = [
  "The Nine Centres",
  "The 36 Channels",
  "Types & Authority",
  "Gates & Lines",
] as const;

export const FLASHCARDS: readonly Flashcard[] = [
  // The Nine Centres
  {
    id: "centres-01-what-defines",
    deck: "The Nine Centres",
    front: "What makes a centre defined in a bodygraph?",
    back: "A centre is defined when at least one complete channel reaches it, which means both gates of that channel carry an activation. A single activated gate whose partner is missing is a hanging gate and defines nothing.",
    tags: ["centres", "definition", "channels"],
    difficulty: 1,
  },
  {
    id: "centres-02-head-and-ajna-gates",
    deck: "The Nine Centres",
    front: "Which gates belong to the Head, and which belong to the Ajna?",
    back: "The Head holds gates 61, 63 and 64. The Ajna holds gates 4, 11, 17, 24, 43 and 47.",
    tags: ["centres", "head", "ajna", "gates"],
    difficulty: 1,
  },
  {
    id: "centres-03-throat-gates",
    deck: "The Nine Centres",
    front: "Which gates belong to the Throat, and how many are there?",
    back: "Eleven gates: 8, 12, 16, 20, 23, 31, 33, 35, 45, 56 and 62. That is the largest gate family of any centre.",
    tags: ["centres", "throat", "gates"],
    difficulty: 1,
  },
  {
    id: "centres-04-g-centre-gates",
    deck: "The Nine Centres",
    front: "Which gates belong to the G Center?",
    back: "Gates 1, 2, 7, 10, 13, 15, 25 and 46.",
    tags: ["centres", "g-centre", "gates"],
    difficulty: 1,
  },
  {
    id: "centres-05-heart-gates",
    deck: "The Nine Centres",
    front: "Which gates belong to the Heart centre?",
    back: "Gates 21, 26, 40 and 51.",
    tags: ["centres", "heart", "gates"],
    difficulty: 1,
  },
  {
    id: "centres-06-spleen-gates",
    deck: "The Nine Centres",
    front: "Which gates belong to the Spleen?",
    back: "Gates 18, 28, 32, 44, 48, 50 and 57.",
    tags: ["centres", "spleen", "gates"],
    difficulty: 1,
  },
  {
    id: "centres-07-solar-plexus-gates",
    deck: "The Nine Centres",
    front: "Which gates belong to the Solar Plexus?",
    back: "Gates 6, 22, 30, 36, 37, 49 and 55.",
    tags: ["centres", "solar-plexus", "gates"],
    difficulty: 1,
  },
  {
    id: "centres-08-sacral-gates",
    deck: "The Nine Centres",
    front: "Which gates belong to the Sacral?",
    back: "Gates 3, 5, 9, 14, 27, 29, 34, 42 and 59.",
    tags: ["centres", "sacral", "gates"],
    difficulty: 1,
  },
  {
    id: "centres-09-root-gates",
    deck: "The Nine Centres",
    front: "Which gates belong to the Root?",
    back: "Gates 19, 38, 39, 41, 52, 53, 54, 58 and 60.",
    tags: ["centres", "root", "gates"],
    difficulty: 1,
  },
  {
    id: "centres-10-split-definition",
    deck: "The Nine Centres",
    front: "The defined centres in a chart fall into two groups that no channel connects. What is that called?",
    back: "Split Definition: two separate connected components of defined centres. One component is Single, three is Triple Split, four is Quadruple Split, and a chart with no defined centre at all is a Reflector. Definition is counted from complete channels only, never from hanging gates.",
    tags: ["centres", "definition", "split"],
    difficulty: 1,
  },
  {
    id: "centres-11-gate-10-trap",
    deck: "The Nine Centres",
    front: "Someone insists Gate 10 belongs to the Throat because its channels reach the Throat. Where does Gate 10 actually sit, and what are those channels?",
    back: "Gate 10 belongs to the G Center. Its three channels are 10-20 Awakening (G to Throat), 10-34 Exploration (G to Sacral) and 10-57 Perfected Form (G to Spleen).",
    tags: ["centres", "gate-10", "integration"],
    difficulty: 2,
  },
  {
    id: "centres-12-gate-28-trap",
    deck: "The Nine Centres",
    front: "Gate 28 is activated and its channel ends at the Root. Which centre holds Gate 28, and which holds the other end?",
    back: "Gate 28 belongs to the Spleen and its partner Gate 38 belongs to the Root. The 28-38 channel is called Struggle and it runs Spleen to Root.",
    tags: ["centres", "gate-28", "spleen"],
    difficulty: 2,
  },
  {
    id: "centres-13-gate-20-and-57",
    deck: "The Nine Centres",
    front: "A chart shows Gate 20 and Gate 57 activated. Which centres do they define, and what is the channel?",
    back: "Gate 20 sits in the Throat and Gate 57 in the Spleen, so the complete 20-57 channel, The Brain Wave, defines both centres. Both gates belong to the Integration cluster and each one belongs to three channels.",
    tags: ["centres", "integration", "throat", "spleen"],
    difficulty: 2,
  },
  {
    id: "centres-14-open-sacral",
    deck: "The Nine Centres",
    front: "Your Sacral is open and you keep agreeing to things you cannot sustain. What is the open Sacral doing?",
    back: "An open Sacral amplifies and reflects the life force around you, so you can run on borrowed energy and only feel the cost later. Its not-self theme is not knowing when enough is enough, which is why the yes has to be tested against a real response before it is spoken.",
    tags: ["centres", "sacral", "open"],
    difficulty: 3,
  },
  {
    id: "centres-15-open-head",
    deck: "The Nine Centres",
    front: "What does an open Head centre feel like from the inside?",
    back: "You take in the mental pressure around you and turn it up, so other people's questions arrive as your own urgent business. The wisdom is discrimination: you can feel which questions are worth answering and let the rest pass. The trap is spending a life resolving questions that were never yours.",
    tags: ["centres", "head", "open"],
    difficulty: 3,
  },
  {
    id: "centres-16-open-g-centre",
    deck: "The Nine Centres",
    front: "What does an open G Center ask of you?",
    back: "Identity and direction are not fixed in you, so you take on the shape of the places and people around you, which makes you adaptable and hard to pin down. The wisdom is noticing where you feel at home rather than deciding who you are. The trap is a lifelong search for a self that was never meant to be fixed.",
    tags: ["centres", "g-centre", "open"],
    difficulty: 3,
  },

  // The 36 Channels
  {
    id: "channels-01-when-defined",
    deck: "The 36 Channels",
    front: "When is a channel defined, and what is a hanging gate?",
    back: "A channel is defined only when both of its gates carry an activation. If one gate is activated and the other is not, that gate is a hanging gate: it defines nothing and waits for its partner.",
    tags: ["channels", "definition", "hanging-gates"],
    difficulty: 1,
  },
  {
    id: "channels-02-gate-membership",
    deck: "The 36 Channels",
    front: "How many channels are there, and how many gates belong to more than one of them?",
    back: "There are 36 channels and each one connects two gates. Gates 10, 20, 34 and 57 each belong to three channels in the Integration cluster, and the other 60 gates belong to exactly one channel.",
    tags: ["channels", "integration", "structure"],
    difficulty: 1,
  },
  {
    id: "channels-03-g-to-throat",
    deck: "The 36 Channels",
    front: "Which channels run from the G Center to the Throat?",
    back: "Four: 1-8 Inspiration, 7-31 The Alpha, 10-20 Awakening and 13-33 The Prodigal.",
    tags: ["channels", "g-centre", "throat"],
    difficulty: 1,
  },
  {
    id: "channels-04-sacral-to-root",
    deck: "The 36 Channels",
    front: "Name the channels that connect the Sacral to the Root.",
    back: "Three: 3-60 Mutation, 9-52 Concentration and 42-53 Maturation.",
    tags: ["channels", "sacral", "root"],
    difficulty: 1,
  },
  {
    id: "channels-05-ajna-to-throat",
    deck: "The 36 Channels",
    front: "Which channels connect the Ajna to the Throat?",
    back: "Three: 11-56 Curiosity, 17-62 Acceptance and 23-43 Structuring.",
    tags: ["channels", "ajna", "throat"],
    difficulty: 1,
  },
  {
    id: "channels-06-spleen-to-root",
    deck: "The 36 Channels",
    front: "Which channels run between the Spleen and the Root?",
    back: "Three: 18-58 Judgement, 28-38 Struggle and 32-54 Transformation.",
    tags: ["channels", "spleen", "root"],
    difficulty: 1,
  },
  {
    id: "channels-07-solar-to-root",
    deck: "The 36 Channels",
    front: "Which channels connect the Solar Plexus to the Root?",
    back: "Three: 30-41 Recognition, 39-55 Emoting and 49-19 Synthesis. The last is the same channel whether it is written 19-49 or 49-19.",
    tags: ["channels", "solar-plexus", "root"],
    difficulty: 1,
  },
  {
    id: "channels-08-heart-channels",
    deck: "The 36 Channels",
    front: "Which channels touch the Heart centre?",
    back: "Four: 21-45 Money (Heart to Throat), 25-51 Initiation (G to Heart), 26-44 Surrender (Heart to Spleen) and 37-40 Community (Solar Plexus to Heart).",
    tags: ["channels", "heart", "tribal"],
    difficulty: 1,
  },
  {
    id: "channels-09-ajna-to-head",
    deck: "The 36 Channels",
    front: "Which channels connect the Ajna to the Head?",
    back: "Three: 4-63 Logic, 24-61 Awareness and 47-64 Abstraction.",
    tags: ["channels", "ajna", "head"],
    difficulty: 1,
  },
  {
    id: "channels-10-integration-cluster",
    deck: "The 36 Channels",
    front: "Name the channels formed among gates 10, 20, 34 and 57.",
    back: "10-20 Awakening (G to Throat), 10-34 Exploration (G to Sacral), 10-57 Perfected Form (G to Spleen), 20-34 Charisma (Throat to Sacral), 20-57 The Brain Wave (Throat to Spleen) and 34-57 Power (Sacral to Spleen).",
    tags: ["channels", "integration"],
    difficulty: 1,
  },
  {
    id: "channels-11-20-34-complete",
    deck: "The 36 Channels",
    front: "A chart has Gate 34 activated and Gate 20 activated, with no other activations. Is the 20-34 channel complete, and what does it define?",
    back: "Yes. Both gates carry an activation, so 20-34 Charisma is complete and it defines the Throat and the Sacral, the two centres it runs between.",
    tags: ["channels", "application", "integration"],
    difficulty: 2,
  },
  {
    id: "channels-12-hanging-28",
    deck: "The 36 Channels",
    front: "Gate 28 is activated but Gate 38 is not. Is the 28-38 channel defined, and what is Gate 28 in that state?",
    back: "No. With Gate 38 missing, Gate 28 is a hanging gate and the Struggle channel is not defined. Gate 28 sits in the Spleen and Gate 38 in the Root, so neither centre gains definition from it.",
    tags: ["channels", "application", "hanging-gates"],
    difficulty: 2,
  },
  {
    id: "channels-13-19-49-twice",
    deck: "The 36 Channels",
    front: "A software report lists both 19-49 and 49-19 as defined channels. How many channels does that chart actually have there?",
    back: "One. 49-19 is the same channel as 19-49, written with the lower gate first, and it is called Synthesis. It runs from the Solar Plexus to the Root and cannot be defined twice.",
    tags: ["channels", "application", "synthesis"],
    difficulty: 2,
  },
  {
    id: "channels-14-gate-10-complete",
    deck: "The 36 Channels",
    front: "An artist has 10-57 defined and neither 10-20 nor 10-34. Is her Gate 10 incomplete?",
    back: "No. Gate 10 belongs to three channels and one complete channel is enough to define it. 10-57 Perfected Form runs from the G Center to the Spleen and it defines both of those centres.",
    tags: ["channels", "application", "integration"],
    difficulty: 2,
  },
  {
    id: "channels-15-hanging-gate-feel",
    deck: "The 36 Channels",
    front: "How does a hanging gate behave in a reading?",
    back: "It is a gate switched on with no channel to carry it, so it leans toward its missing partner and can feel like a permanent pull toward something that never quite arrives. It defines nothing on its own, and the work is learning what that particular hunger is asking for.",
    tags: ["channels", "hanging-gates", "interpretation"],
    difficulty: 3,
  },
  {
    id: "channels-16-26-44-surrender",
    deck: "The 36 Channels",
    front: "What does the 26-44 channel describe in practice?",
    back: "Surrender runs from the Heart to the Spleen and carries an instinct for the deal: a tribal memory for who can help and who is worth helping. It works when the offer is made without bargaining, and it turns manipulative when the ego starts keeping score.",
    tags: ["channels", "tribal", "heart", "spleen"],
    difficulty: 3,
  },

  // Types & Authority
  {
    id: "types-01-generator-definition",
    deck: "Types & Authority",
    front: "What defines a Generator?",
    back: "A defined Sacral with no motor connected to the Throat. The strategy is wait to respond, the signature is Satisfaction, the not-self theme is Frustration, and the aura is open and enveloping.",
    tags: ["types", "generator", "sacral"],
    difficulty: 1,
  },
  {
    id: "types-02-manifesting-generator-definition",
    deck: "Types & Authority",
    front: "What separates a Manifesting Generator from a Generator?",
    back: "In both the Sacral is defined, but the Manifesting Generator also has a motor connected to the Throat, and that connection is a path through the graph rather than necessarily a direct channel. The strategy is respond then inform, the signature is Satisfaction and peace, the not-self theme is Frustration and anger, and the aura is open, enveloping and impactive.",
    tags: ["types", "manifesting-generator", "motor"],
    difficulty: 1,
  },
  {
    id: "types-03-manifestor-aura",
    deck: "Types & Authority",
    front: "What defines a Manifestor, and what does the aura do?",
    back: "The Sacral is undefined and a motor is connected to the Throat. The strategy is inform before acting, the signature is Peace, the not-self theme is Anger, and the aura is closed and repelling, pushing others away rather than drawing them in.",
    tags: ["types", "manifestor", "aura"],
    difficulty: 1,
  },
  {
    id: "types-04-projector-definition",
    deck: "Types & Authority",
    front: "What defines a Projector?",
    back: "No Sacral definition and no motor-to-Throat connection, but at least one centre defined. The strategy is wait for the invitation, the signature is Success, the not-self theme is Bitterness, and the aura is focused and absorbing.",
    tags: ["types", "projector", "aura"],
    difficulty: 1,
  },
  {
    id: "types-05-reflector-lunar",
    deck: "Types & Authority",
    front: "What defines a Reflector, and how does a Reflector decide?",
    back: "No centre is defined at all, which is true for roughly one per cent of people. The strategy is wait a lunar cycle, the signature is Surprise, the not-self theme is Disappointment, and the aura is resistant and sampling. The authority is lunar: a full cycle of about 28 to 29 days before a decision settles.",
    tags: ["types", "reflector", "authority", "lunar"],
    difficulty: 1,
  },
  {
    id: "types-06-authority-precedence",
    deck: "Types & Authority",
    front: "What is the order of inner authority, from highest to lowest?",
    back: "Emotional first, then Sacral, then Splenic, then Ego or Heart, then Self-Projected, then Mental or Environmental, and finally Lunar for a Reflector. The highest authority that is present always wins.",
    tags: ["authority", "precedence"],
    difficulty: 1,
  },
  {
    id: "types-07-scenario-sacral-no-throat",
    deck: "Types & Authority",
    front: "Someone has a defined Sacral and no motor-to-Throat connection. Which type are they?",
    back: "Generator. The defined Sacral is the marker, and because no motor reaches the Throat the extra speed of a Manifesting Generator is not present.",
    tags: ["types", "application", "generator"],
    difficulty: 2,
  },
  {
    id: "types-08-scenario-motor-path",
    deck: "Types & Authority",
    front: "A chart has a defined Sacral, and the Root is wired through to the Throat by complete channels. Which type is it?",
    back: "Manifesting Generator. The defined Sacral gives the Generator base, and a motor connected to the Throat by any path, here the Root, makes it manifesting. The connection is a graph path and not necessarily a direct channel.",
    tags: ["types", "application", "manifesting-generator"],
    difficulty: 2,
  },
  {
    id: "types-09-scenario-heart-throat",
    deck: "Types & Authority",
    front: "A chart has Gate 21 and Gate 45 activated, so the 21-45 channel is complete. The Sacral is undefined. Which type is it?",
    back: "Manifestor. 21-45 Money connects the Heart motor to the Throat, and with no Sacral definition that motor-to-Throat configuration is a Manifestor rather than a Manifesting Generator.",
    tags: ["types", "application", "manifestor"],
    difficulty: 2,
  },
  {
    id: "types-10-scenario-projector",
    deck: "Types & Authority",
    front: "There is no Sacral definition and no motor-to-Throat connection, but the Ajna and the Throat are defined. Which type is it?",
    back: "Projector. At least one centre is defined, so it is not a Reflector, and the absence of Sacral definition and of a motor-to-Throat connection rules out the Generator and Manifestor families.",
    tags: ["types", "application", "projector"],
    difficulty: 2,
  },
  {
    id: "types-11-emotional-authority",
    deck: "Types & Authority",
    front: "What does Emotional authority ask of you?",
    back: "With the Solar Plexus defined there is no truth in the now, because you live inside an emotional wave. Clarity arrives only once the wave has run its course, so the practice is to hold the decision until the high and the low have both passed and the same answer remains.",
    tags: ["authority", "emotional", "solar-plexus"],
    difficulty: 3,
  },
  {
    id: "types-12-sacral-authority",
    deck: "Types & Authority",
    front: "What is the Sacral authority's signal?",
    back: "A gut yes or no in the moment, felt in the body before it becomes a sentence, often as a sound or an impulse rather than a thought. It is available only when the Solar Plexus is undefined, and it answers best to a question that has already been asked.",
    tags: ["authority", "sacral"],
    difficulty: 3,
  },
  {
    id: "types-13-splenic-authority",
    deck: "Types & Authority",
    front: "How does Splenic authority speak, and what is its limitation?",
    back: "Quietly, instantly and once. It is a survival knowing that arises in the moment and never repeats itself, so if you talk yourself out of it the information is gone. It is your authority only when neither the Solar Plexus nor the Sacral is defined.",
    tags: ["authority", "splenic", "spleen"],
    difficulty: 3,
  },
  {
    id: "types-14-ego-authority",
    deck: "Types & Authority",
    front: "What is Ego authority asking about, and where does it sit in the order?",
    back: "With the Heart centre defined, the question is what you want and have the will to back with your word and your resources. Ego outranks Self-Projected, so when the Heart is defined the G Center speaking through the Throat does not take precedence.",
    tags: ["authority", "ego", "heart"],
    difficulty: 3,
  },
  {
    id: "types-15-self-projected-authority",
    deck: "Types & Authority",
    front: "How do you hear Self-Projected authority?",
    back: "By saying it aloud to someone who does not need to reply, and listening to your own voice rather than to their reaction. It applies when the G Center is defined and connected to the Throat while the Heart is undefined and no higher authority is present.",
    tags: ["authority", "self-projected", "g-centre"],
    difficulty: 3,
  },
  {
    id: "types-16-mental-authority",
    deck: "Types & Authority",
    front: "What is Mental or Environmental authority?",
    back: "It belongs to a Projector whose definition sits only at or above the Throat, leaving no inner authority in the body. There is no signal to consult, so clarity comes from talking it through with the right people over time and from being in the right environment.",
    tags: ["authority", "mental", "projector"],
    difficulty: 3,
  },

  // Gates & Lines
  {
    id: "gates-01-wheel-start",
    deck: "Gates & Lines",
    front: "Which gate begins the gate wheel, and at what point does it start?",
    back: "Gate 41, Contraction, begins the wheel at 2 degrees of Aquarius, which falls around 22 January and is treated as the Rave New Year. The zodiac used is tropical, not sidereal.",
    tags: ["gates", "wheel", "gate-41"],
    difficulty: 1,
  },
  {
    id: "gates-02-activations",
    deck: "Gates & Lines",
    front: "How many activations appear in a bodygraph, and which bodies produce them?",
    back: "Twenty-six: thirteen on the Personality side and the same thirteen on the Design side. The bodies are the Sun, Earth, Moon, North Node, South Node, Mercury, Venus, Mars, Jupiter, Saturn, Uranus, Neptune and Pluto. The lunar nodes must be the true node, not the mean node.",
    tags: ["gates", "activations", "design"],
    difficulty: 1,
  },
  {
    id: "gates-03-design-arc",
    deck: "Gates & Lines",
    front: "A person is born with the Sun at 15 degrees of Leo. Roughly where was the Sun when their Design chart is cast?",
    back: "About 17 degrees of Taurus. The Design chart is cast for the moment the Sun stood 88 degrees of solar arc earlier, and that is 88 degrees, not 88 days. Fifteen degrees of Leo is 135 degrees of longitude, and 135 minus 88 is 47, which is 17 degrees of Taurus. Earth is always exactly opposite the Sun, and the South Node exactly opposite the North Node.",
    tags: ["gates", "design", "application"],
    difficulty: 2,
  },
  {
    id: "gates-04-names-1-11",
    deck: "Gates & Lines",
    front: "Name the gates from 1 to 11.",
    back: "1 Self-Expression, 2 Direction, 3 Ordering, 4 The Answer, 5 Rhythm, 6 Friction, 7 The Role, 8 Contribution, 9 Focus, 10 Self-Love and 11 Ideas.",
    tags: ["gates", "names"],
    difficulty: 1,
  },
  {
    id: "gates-05-names-12-22",
    deck: "Gates & Lines",
    front: "Name the gates from 12 to 22.",
    back: "12 Caution, 13 The Listener, 14 Power Skills, 15 Extremes, 16 Skills, 17 Opinion, 18 Correction, 19 Wanting, 20 The Now, 21 Control and 22 Grace.",
    tags: ["gates", "names"],
    difficulty: 1,
  },
  {
    id: "gates-06-names-23-33",
    deck: "Gates & Lines",
    front: "Name the gates from 23 to 33.",
    back: "23 Assimilation, 24 Rationalizing, 25 Innocence, 26 The Trickster, 27 Nourishment, 28 The Game Player, 29 Commitment, 30 Desire, 31 Leading, 32 Endurance and 33 Retreat.",
    tags: ["gates", "names"],
    difficulty: 1,
  },
  {
    id: "gates-07-names-34-44",
    deck: "Gates & Lines",
    front: "Name the gates from 34 to 44.",
    back: "34 Power, 35 Change, 36 Crisis, 37 Friendship, 38 The Fighter, 39 Provocation, 40 Aloneness, 41 Contraction, 42 Growth, 43 Insight and 44 Instinct.",
    tags: ["gates", "names"],
    difficulty: 1,
  },
  {
    id: "gates-08-names-45-55",
    deck: "Gates & Lines",
    front: "Name the gates from 45 to 55.",
    back: "45 The Gatherer, 46 The Body, 47 Realization, 48 Depth, 49 Principles, 50 Values, 51 Shock, 52 Stillness, 53 Beginnings, 54 Ambition and 55 Spirit.",
    tags: ["gates", "names"],
    difficulty: 1,
  },
  {
    id: "gates-09-names-56-64",
    deck: "Gates & Lines",
    front: "Name the gates from 56 to 64.",
    back: "56 The Storyteller, 57 Intuition, 58 Vitality, 59 Intimacy, 60 Acceptance, 61 Inner Truth, 62 Precision, 63 Doubt and 64 Confusion.",
    tags: ["gates", "names"],
    difficulty: 1,
  },
  {
    id: "gates-10-lines-1-3",
    deck: "Gates & Lines",
    front: "What do lines 1, 2 and 3 describe?",
    back: "Line 1 is the Investigator, who needs a foundation and finds security through solid ground and research. Line 2 is the Hermit, a natural talent that needs solitude and must be called out by others. Line 3 is the Martyr, who discovers through trial and error and through bonds that break.",
    tags: ["lines", "profile"],
    difficulty: 1,
  },
  {
    id: "gates-11-lines-4-6",
    deck: "Gates & Lines",
    front: "What do lines 4, 5 and 6 describe?",
    back: "Line 4 is the Opportunist, who influences through friendship and network. Line 5 is the Heretic, expected to deliver a practical universal fix and carrying other people's projections. Line 6 is the Role Model, whose wisdom is earned by living it and then lived as an example across three phases of life.",
    tags: ["lines", "profile"],
    difficulty: 1,
  },
  {
    id: "gates-12-profile-order",
    deck: "Gates & Lines",
    front: "A chart lists the Personality Sun in line 3 and the Design Sun in line 5. What is the profile called, and what angle is it?",
    back: "3/5, the Martyr-Heretic, and it is a right angle profile. A profile is always written as the Personality Sun line first and the Design Sun line second.",
    tags: ["profile", "application", "lines"],
    difficulty: 2,
  },
  {
    id: "gates-13-profile-angles",
    deck: "Gates & Lines",
    front: "Which profiles are right angle, which is juxtaposition, and which are left angle?",
    back: "Right angle: 1/3, 1/4, 2/4, 2/5, 3/5 and 3/6. Juxtaposition: 4/1. Left angle: 4/6, 5/1, 5/2, 6/2 and 6/3. There is no 6/4 profile.",
    tags: ["profile", "angles"],
    difficulty: 1,
  },
  {
    id: "gates-14-profile-3-6",
    deck: "Gates & Lines",
    front: "How does a 3/6 profile tend to live out over a lifetime?",
    back: "The Martyr-Role Model is a right angle profile, so the life is personal before it is useful. The early years are trial and error, with bonds that break as the experiments fail, and line 6 then runs in three phases: a first phase of experimentation, a middle phase of withdrawal and observation, and a final phase lived as an example others can follow.",
    tags: ["profile", "interpretation", "lines"],
    difficulty: 3,
  },
  {
    id: "gates-15-profile-2-4",
    deck: "Gates & Lines",
    front: "What does a 2/4 profile look like in practice?",
    back: "Hermit-Opportunist, a right angle profile. The natural gift is real but only develops in solitude, and it reaches the world through the network of friends and acquaintances who already trust the person. Strangers rarely call it out, because the opportunity usually arrives through someone who knows them.",
    tags: ["profile", "interpretation", "lines"],
    difficulty: 3,
  },
  {
    id: "gates-16-profile-5-1",
    deck: "Gates & Lines",
    front: "What is a 5/1 profile asked to carry?",
    back: "The Heretic-Investigator is a left angle profile, so others project a universal fix onto it and expect practical salvation. That projection only holds if the 1's foundation is genuinely there, and without solid research and preparation the 5 is blamed when the promise fails.",
    tags: ["profile", "interpretation", "lines"],
    difficulty: 3,
  },
] satisfies readonly Flashcard[];
